{
 "title": "DaemonSet",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "daemonset_namespace",
    "label": "Namespace",
    "query": "label_values(kube_daemonset_metadata_generation, exported_namespace)"
   },
   {
    "name": "daemonset_name",
    "label": "DaemonSet",
    "query": "label_values(kube_daemonset_metadata_generation{exported_namespace=\"$daemonset_namespace\"}, daemonset)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"$daemonset_namespace\",pod_name=~\"$daemonset_name.*\",image!=\"\"}) / sum (container_spec_memory_limit_bytes{pod_name=~\"$daemonset_name.*\",image!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$daemonset_name.*$\"}[2m])) / sum(container_spec_cpu_quota{pod_name=~\"^$daemonset_name.*$\",image!=\"\"} / container_spec_cpu_period{pod_name=~\"^$daemonset_name.*$\",image!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_usage_bytes{namespace=\"$daemonset_namespace\",pod_name=~\"$daemonset_name.*\",image!=\"\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$daemonset_name.*$\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network in",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$daemonset_name.*$\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^$daemonset_name.*$\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Available replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",exported_namespace=\"$daemonset_namespace\"}) / sum(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\",exported_namespace=\"$daemonset_namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\", exported_namespace=\"$daemonset_namespace\"})"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_daemonset_metadata_generation{daemonset=\"$daemonset_name\",exported_namespace=\"$daemonset_namespace\"})"
    }
   ]
  },
  {
   "title": "Replicas over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_daemonset_status_current_number_scheduled{daemonset=\"$daemonset_name\",exported_namespace=\"$daemonset_namespace\"})",
     "legendFormat": "current replicas"
    },
    {
     "expr": "min(kube_daemonset_status_number_available{daemonset=\"$daemonset_name\",exported_namespace=\"$daemonset_namespace\"})",
     "legendFormat": "available"
    },
    {
     "expr": "max(kube_daemonset_status_number_unavailable{daemonset=\"$daemonset_name\",exported_namespace=\"$daemonset_namespace\"})",
     "legendFormat": "unavailable"
    },
    {
     "expr": "max(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset_name\",exported_namespace=\"$daemonset_namespace\"})",
     "legendFormat": "desired"
    }
   ]
  }
 ]
}