{
 "title": "DNS Performances",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "DNS queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubedns_dnsmasq_hits [2m])) + sum(rate(kubedns_dnsmasq_misses [2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_hits [2m]))",
     "legendFormat": "Cache hits"
    },
    {
     "expr": "sum(rate(kubedns_dnsmasq_misses [2m]))",
     "legendFormat": "Cache misses"
    }
   ]
  },
  {
   "title": "DNS queries per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubedns_dnsmasq_hits [2m]) + rate(kubedns_dnsmasq_misses [2m])"
    }
   ]
  },
  {
   "title": "Dns Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubedns_probe_dnsmasq_errors [2m])"
    },
    {
     "expr": "rate(kubedns_probe_kubedns_errors [2m])"
    }
   ]
  },
  {
   "title": "DNS errors count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubedns_dnsmasq_errors" }
   ]
  },
  {
   "title": "Restart count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts{exported_pod=~\"kube-dns.*\"}"
    }
   ]
  },
  {
   "title": "Terminated count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_terminated{exported_pod=~\"kube-dns.*\"}"
    }
   ]
  }
 ]
}