{
 "title": "k8s-Cluster",
 "description": "Dashboard to get an overview of one server",
 "tags": [ "Infrastructure" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "sum(ALERTS{severity!=\"information\",severity!=\"none\", alertstate=\"firing\",alerting_target=\"infrastructure\"})"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "k8s:cluster:memory_usage_percent"
      }
     ]
    },
    {
     "title": "CPU allocation",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "((sum(max(kube_pod_container_resource_requests_cpu_cores and on(node)(max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node)) ) by(exported_pod)))/(sum(max(kube_node_status_allocatable_cpu_cores and on(node)(max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node))) by (node))))*100"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "((sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m]) and on(instance)(label_replace (max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node),\"instance\", \"$1.$2.$3.$4:4194\",\"node\",\"ip-(.*)-(.*)-(.*)-(.*).ec2.internal\"))))/(sum(max(kube_node_status_allocatable_cpu_cores and on(node)(max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node))) by (node))))*100"
      }
     ]
    },
    {
     "title": "Node count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "cluster_autoscaler_nodes_count", "legendFormat": "{{ state }}" },
      {
       "expr": "cluster_autoscaler_unschedulable_pods_count",
       "legendFormat": "Unschedulable pods"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes and on(instance)( (label_replace                    (max           (kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node),             \"instance\",               \"$1.$2.$3.$4:9100\",\"node\",\"ip-(.*)-(.*)-(.*)-(.*).ec2.internal\"))) )- sum(node_memory_MemFree_bytes and on(instance)( (label_replace                    (max           (kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node),             \"instance\",               \"$1.$2.$3.$4:9100\",\"node\",\"ip-(.*)-(.*)-(.*)-(.*).ec2.internal\"))) )",
       "legendFormat": "memory free"
      },
      {
       "expr": "sum(max(kube_node_status_allocatable_memory_bytes and on(node)(max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node)))by (node))",
       "legendFormat": "Max memory allocatable"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "sum(max(kube_pod_container_resource_requests_cpu_cores and on(node)(max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node)) ) by(exported_pod))",
       "legendFormat": "CPU request"
      },
      {
       "expr": "sum(max(kube_node_status_allocatable_cpu_cores and on(node)(max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node))) by (node))",
       "legendFormat": "CPU max allocation "
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m]) and on(instance)(label_replace (max(kube_node_labels{label_kubernetes_io_role!=\"master\"})by (node),\"instance\", \"$1.$2.$3.$4:4194\",\"node\",\"ip-(.*)-(.*)-(.*)-(.*).ec2.internal\")))",
       "legendFormat": "CPU Utilization"
      }
     ]
    },
    {
     "title": "Top 5 Pod Memory usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,max(container_memory_usage_bytes{image!=\"\"}) by (namespace ,container_name))",
       "legendFormat": "{{namespace}}/{{container_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Pod CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "topk(5,max(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (namespace ,container_name))",
       "legendFormat": "{{namespace}}/{{container_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Namespace Memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(5,max(container_memory_usage_bytes{image!=\"\"}) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Top 5 namespace CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "topk(5,max(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (namespace))",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Oversized Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oversized containers",
     "type": "table",
     "description": "List of container using less than the half requested cpu",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (namespace,pod_container) (   label_join(rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\"}[5m]), \"pod_container\", \"/\", \"pod_name\",\"container_name\") )   / on (pod_container) group_left  avg by (container_name,pod_container)(  label_join(   label_replace(kube_pod_container_resource_requests_cpu_cores{},\"container_name\",\"$1\",\"container\",\"(.*)\"),   \"pod_container\",   \"/\",   \"exported_pod\",   \"container\"  ) ) * 100 < 50",
       "legendFormat": "{{pod_container}}"
      }
     ]
    }
   ]
  }
 ]
}