{
 "title": "Kiam",
 "description": "Kiam cache, response & health metrics",
 "tags": [
  "Kubernetes",
  "Kiam"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Kiam Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Credentials - Cache Hit",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_server_credentialscache_cachehit*100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Credentials - Cache miss",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_server_credentialscache_cachemiss*100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Get pod role requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_server_server_getpodrole *100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Credentials cache size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_server_credentialscache_size",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Credentials - Error issuing",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_server_credentialscache_errorissuing",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sts assume role request",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_server_stsassumerole_executingrequests",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Get role credential request",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_server_server_getrolecredentials*100",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kiam Server Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",container_name=~\"kiam\",pod_name=~\"kiam-server.*\"}[2m] ) )",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Kiam Agent Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",container_name=~\"kiam\",pod_name=~\"kiam-agent.*\"}[2m] ) )",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Kube-apiserver Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",container_name=~\"kube-apiserver\",pod_name=~\"kube-apiserver.*\"}[2m] ) )",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kiam Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Credentials fetch succeeded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_agent_handlerresponse_credentials_2xx *100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Credential Fetch failed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kiam_agent_handlerresponse_credentials_5xx *100",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}