{
 "title": "Logging - logstash",
 "description": "Logstash monitoring via prometheus",
 "tags": [
  "prometheus",
  "elasticsearch",
  "logstash"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "15s,30s,1m,5m,1h,6h,1d" },
   {
    "name": "deployment_namespace",
    "label": "Namespace",
    "query": "label_values(kube_deployment_metadata_generation, exported_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "RESSOURCES",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"logstash.*\",container_name=\"logstash\",namespace=\"$deployment_namespace\"}[2m] )",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"logstash.*\",container=\"logstash\",exported_namespace=\"$deployment_namespace\"})",
       "legendFormat": "CPU request"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"logstash.*\",container=\"logstash\",exported_namespace=\"$deployment_namespace\"})",
       "legendFormat": "CPU limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{container_name!=\"POD\",pod_name=~\"logstash.*\",container_name=\"logstash\",namespace=\"$deployment_namespace\",image!=\"\"}",
       "legendFormat": "{{ pod_name }}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"logstash.*\",container=\"logstash\",exported_namespace=\"$deployment_namespace\"})",
       "legendFormat": "Memory request"
      },
      {
       "expr": "avg(container_spec_memory_limit_bytes{container_name!=\"POD\",pod_name=~\"logstash.*\",container_name=\"logstash\",namespace=\"$deployment_namespace\",image!=\"\"})",
       "legendFormat": "Memory limit "
      }
     ]
    }
   ]
  },
  {
   "title": "PIPELINE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(logstash_pipeline_events_duration_in_millis{namespace=\"$deployment_namespace\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Events in rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(logstash_pipeline_events_filtered{namespace=\"$deployment_namespace\"}[10m]))",
       "legendFormat": "Filtered"
      },
      {
       "expr": "sum(rate(logstash_pipeline_events_in{namespace=\"$deployment_namespace\"}[10m]))",
       "legendFormat": "In"
      },
      {
       "expr": "sum(rate(logstash_pipeline_events_out{namespace=\"$deployment_namespace\"}[10m]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Events filtered rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(logstash_pipeline_events_filtered{namespace=\"$deployment_namespace\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Events out rate",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(logstash_pipeline_events_out{namespace=\"$deployment_namespace\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PLUGINS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration rate for input",
     "type": "graph",
     "description": "Time to push input in queue",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(logstash_pipeline_plugins_inputs_events_queue_push_duration_in_millis{namespace=\"$deployment_namespace\"}[$interval])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Duration rate for output",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(logstash_pipeline_plugins_outputs_events_duration_in_millis{namespace=\"$deployment_namespace\"}[$interval])",
       "legendFormat": "{{pod}}:{{name}}"
      }
     ]
    },
    {
     "title": "Events Out rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(logstash_pipeline_plugins_outputs_events_in{namespace=\"$deployment_namespace\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Events In rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(logstash_pipeline_plugins_inputs_events_out{namespace=\"$deployment_namespace\"}[$interval])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap used",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percent", "label": "Heap" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "expr": "logstash_jvm_mem_heap_used_percent{namespace=\"$deployment_namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "expr": "logstash_process_open_file_descriptors{namespace=\"$deployment_namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "GCs" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "expr": "(delta(logstash_jvm_gc_collectors_young_collection_count{namespace=\"$deployment_namespace\"} [$interval]) + delta(logstash_jvm_gc_collectors_young_collection_count{namespace=\"$deployment_namespace\"} [$interval])) ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "s", "label": "GCs" }
     ],
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "avg",
       "downsampleFillPolicy": "none",
       "expr": "rate(logstash_jvm_gc_collectors_old_collection_time_in_millis{namespace=\"$deployment_namespace\"}[$interval])",
       "legendFormat": "Old GC - {{pod}}"
      },
      {
       "expr": "rate(logstash_jvm_gc_collectors_young_collection_time_in_millis{namespace=\"$deployment_namespace\"}[$interval])",
       "legendFormat": "Young GC - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}