{
 "title": "Nodes",
 "description": "Dashboard to get an overview of one server",
 "tags": [ "Infrastructure" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_ip",
    "label": "Server",
    "query": "label_values(node_cpu_seconds_total, instance)"
   },
   {
    "name": "server_name",
    "query": "query_result(node_uname_info{instance=\"$server_ip:9100\"})"
   },
   { "name": "domain", "query": "dev.cloud.coveo.com" },
   {
    "name": "role",
    "query": "query_result(max(kube_node_labels{label_kubernetes_io_hostname=\"$server_name.$domain\"})by (label_kubernetes_io_role))"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "avg by (mode) (irate(node_cpu_seconds_total{instance=\"$server_ip:9100\",mode!=\"idle\"}[5m])*100)> 1",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "sum(max(kube_pod_container_resource_requests_cpu_cores{node=\"$server_name.ec2.internal\"}) by (container))",
     "legendFormat": "Cpu requests"
    },
    {
     "expr": "max(kube_node_status_allocatable_cpu_cores{node=\"$server_name.ec2.internal\"})",
     "legendFormat": "Max Cpu allocation"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",instance=\"$server_ip:4194\"}[5m]) )",
     "legendFormat": "Cpu utilization"
    }
   ]
  },
  {
   "title": "Cpu allocation",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",instance=\"$server_ip:4194\"}[5m]) )/ max(kube_node_status_allocatable_cpu_cores{node=\"$server_name.ec2.internal\"})*100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(node_memory_MemTotal_bytes{instance=\"$server_ip:9100\"})",
     "legendFormat": "max memory allocatable"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server_ip:9100\"} - node_memory_MemFree_bytes{instance=\"$server_ip:9100\"} ",
     "legendFormat": "memory used"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$server_ip:9100\"} - node_memory_MemFree_bytes{instance=\"$server_ip:9100\"})/ node_memory_MemTotal_bytes{instance=\"$server_ip:9100\"}) * 100"
    }
   ]
  },
  {
   "title": "Top 5 Pod cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "topk(5,max(rate(container_cpu_usage_seconds_total{image!=\"\",instance=\"$server_ip:4194\"}[5m])) by (container_name))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,max(container_memory_usage_bytes{image!=\"\",instance=\"$server_ip:4194\"}) by (container_name))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_read_bytes_total{instance=\"$server_ip:9100\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_written_bytes_total{instance=\"$server_ip:9100\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_seconds_total{instance=\"$server_ip:9100\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$server_ip:9100\"}) - sum(node_filesystem_avail_bytes{device!=\"rootfs\",instance=\"$server_ip:9100\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=\"$server_ip:9100\"})"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$server_ip:9100\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$server_ip:9100\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}