{
 "title": "Pods",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, exported_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{exported_namespace=\"$namespace\"}, exported_pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{exported_namespace=\"$namespace\", exported_pod=\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=\"$pod\", container_name=~\"$container\", container_name!=\"POD\",image!=\"\"})",
     "legendFormat": "Memmory usage {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{exported_pod=\"$pod\",container=~\"$container\"}",
     "legendFormat": "Memory request {{ container }}"
    },
    {
     "expr": "container_spec_memory_limit_bytes{pod_name=\"$pod\", container_name!=\"POD\",container_name=~\"$container\",image!=\"\"}",
     "legendFormat": "Memory limit {{ container_name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=\"$pod\",container_name=~\"$container\"}[2m] ) )",
     "legendFormat": "CPU Utilization {{ container_name }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{exported_pod =\"$pod\",container=~\"$container\"}",
     "legendFormat": "CPU request {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{exported_pod =\"$pod\",container=~\"$container\"}",
     "legendFormat": "CPU limit {{ container }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_receive_bytes_total{pod_name=\"$pod\",image!=\"\"}[2m]) ))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}