{
 "title": "QTS Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "queue_throttling_service_nb_can_convert",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(queue_throttling_service_nb_can_convert)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "queue_throttling_service_nb_ready_dpm_queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(queue_throttling_service_nb_ready_dpm_queue)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "queue_throttling_service_refresh_duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(queue_throttling_service_refresh_duration) by (rabbit_server)",
     "legendFormat": "{{rabbit_server}}"
    }
   ]
  }
 ]
}