{
 "title": "RabbitMQ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(rabbitmq_running, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Socket used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{service=~\"$service\"} ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "File Descriptor used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_fd_used{service=~\"$service\"} ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total number of queues in use",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queuesTotal{service=~\"$service\"} ",
     "legendFormat": "Total Queues"
    }
   ]
  },
  {
   "title": "Total messages in queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_total{service=~\"$service\"} ",
     "legendFormat": "Total messages in Queues"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_disk_free{service=~\"$service\"} ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory used by nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{service=~\"$service\"} ",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}