{
 "title": "RabbitMQ Queues Status",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(rabbitmq_running, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 most total messages in queues DOC and Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages{queue=~\".*Doc|.*pool\",service=~\"$service\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Top 10 most total messages in queues Sync and Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages{queue=~\".*Sync|.*Job\",service=~\"$service\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Top 10 most ready messages in queues Sync and Job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages_ready{queue=~\".*Sync|.*Job\",service=~\"$service\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Top 10 most ready messages in queues Doc and pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages_ready{queue=~\".*Doc|.*pool\",service=~\"$service\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Top 10 most unack messages in queues DOC and Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages_unacknowledged{queue=~\".*Doc|.*pool\",service=~\"$service\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Top 10 most unack messages in queues Sync and Job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rabbitmq_queue_messages_unacknowledged{queue=~\".*Sync|.*Job\",service=~\"$service\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total messages in queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(rabbitmq_queue_messages)" }
   ]
  },
  {
   "title": "Total messages ready in queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready)"
    }
   ]
  },
  {
   "title": "Total messages unack in queues",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged)"
    }
   ]
  }
 ]
}