{
 "title": "Sentry",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pod Web count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=~\"sentry-web.*\"}",
     "legendFormat": "{{hpa}}"
    }
   ]
  },
  {
   "title": "Pod Worker count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=~\"sentry-worker.*\"}",
     "legendFormat": "{{hpa}}"
    }
   ]
  },
  {
   "title": "Cpu usage (Web)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name,container_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"sentry-web.*\"}[2m] ) )",
     "legendFormat": "{{pod_name}}/{{container_name}}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_cpu_cores{exported_pod =~\"sentry-web.*\"})",
     "legendFormat": "CPU Limits {{container}}"
    }
   ]
  },
  {
   "title": "Cpu Usage (Cron)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"sentry-cron.*\"}[2m] ) )",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (container_name) (kube_pod_container_resource_requests_cpu_cores{exported_pod =~\"sentry-cron.*\"})",
     "legendFormat": "Cpu requested"
    },
    {
     "expr": "avg by (container_name) (kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"sentry-cron.*\"})",
     "legendFormat": "Cpu limit"
    }
   ]
  },
  {
   "title": "Cpu Usage (Worker)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=~\"sentry-worker.*\"}[2m] ) )",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (container_name) (kube_pod_container_resource_requests_cpu_cores{exported_pod =~\"sentry-worker.*\"})",
     "legendFormat": "Cpu request"
    },
    {
     "expr": "avg by (container_name) (kube_pod_container_resource_limits_cpu_cores{exported_pod=~\"sentry-worker.*\"})",
     "legendFormat": "Cpu limit"
    }
   ]
  },
  {
   "title": "Memory usage (Web)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"sentry-web.*\", container_name!=\"POD\", image!=\"\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (container_name) (kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"sentry-web.*\"})",
     "legendFormat": "Memory requested"
    },
    {
     "expr": "avg by (container_name) (container_spec_memory_limit_bytes{pod_name=~\"sentry-web.*\", container_name!=\"POD\", image!=\"\"})",
     "legendFormat": "Memory limit"
    }
   ]
  },
  {
   "title": "Memory usage (Cron)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"sentry-cron.*\", container_name!=\"POD\", image!=\"\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (container_name) (kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"sentry-cron.*\"})",
     "legendFormat": "Memory requested"
    },
    {
     "expr": "avg by (container_name) (container_spec_memory_limit_bytes{pod_name=~\"sentry-cron.*\", container_name!=\"POD\", image!=\"\"})",
     "legendFormat": "Memory limit"
    }
   ]
  },
  {
   "title": "Memory usage (Worker)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{pod_name=~\"sentry-worker.*\", container_name!=\"POD\", image!=\"\"})",
     "legendFormat": "{{pod_name}}"
    },
    {
     "expr": "avg by (container_name) (kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"sentry-worker.*\"})",
     "legendFormat": "Memory requested"
    },
    {
     "expr": "avg by (container_name) (container_spec_memory_limit_bytes{pod_name=~\"sentry-worker.*\", container_name!=\"POD\", image!=\"\"})",
     "legendFormat": "Memory limit"
    }
   ]
  },
  {
   "title": "Buffer pending size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sentry_buffer_pending_size{quantile=\"0.99\"}",
     "legendFormat": "Buffer size"
    }
   ]
  },
  {
   "title": "Job delay",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sentry_jobs_delay{quantile=\"0.99\"}",
     "legendFormat": "Job delay"
    }
   ]
  },
  {
   "title": "Redis - Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * (avg(redis_memory_used_bytes{job=~\"sentry.*\"})  / avg(redis_memory_max_bytes{job=~\"sentry.*\"}) )",
     "legendFormat": "% use"
    }
   ]
  },
  {
   "title": "DB - Cpu Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=~\".*sentry\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "DB - Free memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{dbinstance_identifier=~\".*sentry\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "DB - Free disk space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{dbinstance_identifier=~\".*sentry\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  }
 ]
}