{
 "title": "Security Store Service dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Rate of call per second",
   "type": "graph",
   "description": "This is the number of call per second made to the Security Store Service.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(security_store_service_method_count[2m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Rate of request over 1 second",
   "type": "graph",
   "description": "This is the rate of request with a duration over 1 second",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(security_store_service_method_bucket{le=\"+Inf\"}[2m])   - ignoring(le) rate(security_store_service_method_bucket{le=\"1.0\"}[2m]))  by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Total number of organization",
   "type": "graph",
   "description": "This is the total number of organization.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(security_store_service_number_of_organization_total) by (job)",
     "legendFormat": "Total number of organization"
    }
   ]
  },
  {
   "title": "Total number of security identities",
   "type": "graph",
   "description": "This is the number total of security identities.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(security_store_service_number_of_security_identities_total) by (job)",
     "legendFormat": "Total number of security identities"
    }
   ]
  }
 ]
}