{
 "title": "UA dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "UA average request time in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(jetty_dispatched_time_seconds_total{endpoint=\"https\", job=~\"uawriteservice|uareadservice\"}[2m]))/sum(rate(jetty_dispatched_total{endpoint=\"https\", job=~\"uawriteservice|uareadservice\"}[2m]))"
    }
   ]
  },
  {
   "title": "UA Write service average request time in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(jetty_dispatched_time_seconds_total{endpoint=\"https\", job=\"uawriteservice\"}[2m]))/sum(rate(jetty_dispatched_total{endpoint=\"https\", job=\"uawriteservice\"}[2m]))"
    }
   ]
  },
  {
   "title": "UA Read service average request time in seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum(rate(jetty_dispatched_time_seconds_total{endpoint=\"https\", job=\"uareadservice\"}[2m])) /   sum(rate(jetty_dispatched_total{endpoint=\"https\", job=\"uareadservice\"}[2m]))"
    }
   ]
  },
  {
   "title": "UA request count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jetty_requests_total{endpoint=\"https\", job=~\"uawriteservice|uareadservice\"}[2m]))"
    }
   ]
  },
  {
   "title": "UA Write service responses by type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jetty_responses_total{job=\"uawriteservice\", endpoint = \"https\"}[2m])) by (code)"
    }
   ]
  },
  {
   "title": "UA Read service responses by type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jetty_responses_total{job=\"uareadservice\", endpoint = \"https\"}[2m])) by (code)"
    }
   ]
  }
 ]
}